---
title: "Formative Assessment 3"
author: "SINOCRUZ, ARVIE"
date: "2025-09-14"
output: pdf_document
---

## Necessary packages
```{r}
library(moments)
library(knitr)
```

## Data
```{r}
scores <- c(
  88, 45, 53, 86, 33, 86, 85, 30, 89, 53, 41, 96, 56, 38, 62,
  71, 51, 86, 68, 29, 28, 47, 33, 37, 25, 36, 33, 94, 73, 46,
  42, 34, 79, 72, 88, 99, 82, 62, 57, 42, 28, 55, 67, 62, 60,
  96, 61, 57, 75, 93, 34, 75, 53, 32, 28, 73, 51, 69, 91, 35)
```
  
## Descriptive statistics
```{r}
n <- length(scores)
mode_val <- as.numeric(names(sort(-table(scores)))[1])
median_val <- median(scores)
mean_val <- mean(scores)
std_val <- sd(scores)
var_val <- var(scores)
skew_val <- skewness(scores)
kurt_val <- kurtosis(scores) - 3  
```

## Percentiles
```{r}
q1 <- quantile(scores, 0.25)
q2 <- quantile(scores, 0.50)
q3 <- quantile(scores, 0.75)
d9 <- quantile(scores, 0.90)
p95 <- quantile(scores, 0.95)
```

# Building the table
```{r}
descriptive_stats <- data.frame(
  Statistic = c(
    "Valid",
    "Mode",
    "Median",
    "Mean",
    "Std. Deviation",
    "Variance",
    "Skewness",
    "Kurtosis",
    "Minimum",
    "Maximum",
    "25th percentile",
    "50th percentile",
    "75th percentile",
    "90th percentile",
    "95th percentile"
  ),
  Score = c(
    n,
    mode_val,
    median_val,
    mean_val,
    std_val,
    var_val,
    skew_val,
    kurt_val,
    min(scores),
    max(scores),
    q1,
    q2,
    q3,
    d9,
    p95
  )
)
```

```{r}
# Print table (simple, works in all R versions)
knitr::kable(
  descriptive_stats,
  format = "latex",
  booktabs = TRUE,
  caption = "Descriptive Statistics of Test Scores",
  align = c("l","r")
)
```
